server:
  port: 8083

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka/
    register-with-eureka: true

spring:
  application:
    name: auth
  jpa:
    database: DERBY
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.DerbyDialect
  jmx:
    enable: false
  datasource:
    driver-class-name: org.apache.derby.jdbc.ClientDriver
    url: jdbc:derby://10.10.11.158:1527/home/databases/sres_db
    username: root
    password: Sermed159#%&