server:
  port: 8082

spring:
  application:
    name: course
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.Oracle10gDialect
  jmx:
    enable: false
  datasource:
    url: jdbc:oracle:thin:@10.10.11.3:1521:prod
    username: SERMED_PE
    password: S3rm3d@p3
